from typing import Protocol, runtime_checkable


@runtime_checkable
class Repository(Protocol):
    """Abstract repository interface for all database backends."""

    async def create_scan_run(self, scan_run: dict) -> dict: ...

    async def update_scan_run(self, scan_id: str, updates: dict) -> dict: ...

    async def get_scan_run(self, scan_id: str) -> dict | None: ...

    async def list_scan_runs(self, limit: int = 20) -> list[dict]: ...

    async def create_lead(self, lead: dict) -> dict: ...

    async def create_leads_batch(self, leads: list[dict]) -> list[dict]: ...

    async def get_lead(self, lead_id: str) -> dict | None: ...

    async def update_lead(self, lead_id: str, updates: dict) -> dict: ...

    async def list_leads(
        self,
        filters: dict,
        sort_by: str,
        limit: int,
        offset: int,
    ) -> list[dict]: ...

    async def get_existing_lead_titles(self, limit: int = 500) -> list[str]: ...
